---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/creates
  label: Creates
  create: all
  match: "**/*"
- type: directory
  path: site/content/thinks
  label: Thinks
  create: all
  match: "**/*"
- type: directory
  path: site/content/created
  label: Created
  create: all
  match: "**/*"
- type: directory
  path: site/content/is
  label: Is
  create: all
  match: "**/*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
